{{- if .Values.imageUpdater.enabled }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: {{ include "app-with-autoupdate-and-ingress.fullname" . }}
spec:
  image: {{ .Values.image.repository}}
  interval: 5m0s
  {{ - if .Values.image.pullSecret ne "" }}
  secretRef:
    name: {{ .Values.image.pullSecret }}
  {{- end }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: {{ include "app-with-autoupdate-and-ingress.fullname" . }}
spec:
  imageRepositoryRef:
    name: {{ include "app-with-autoupdate-and-ingress.fullname" . }}
  filterTags:
    {{- toYaml .Values.imageUpdater.filterTags | nindent 4 }}
  policy:
    {{- toYaml .Values.imageUpdater.policy | nindent 4 }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: {{ include "app-with-autoupdate-and-ingress.fullname" . }}
spec:
  git:
    checkout:
      ref:
        branch: {{ .Values.imageUpdater.source.branch}}
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{`[skip ci] {{range .Updated.Images}}{{println .}}{{end}}`}}'
    push:
      branch: {{ .Values.imageUpdater.source.branch }}
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: {{ .Values.imageUpdater.source.name }}
    namespace: {{ .Values.imageUpdater.source.namespace | default .Release.Namespace }}
  update:
    path: {{ .Values.imageUpdater.source.path }}
    strategy: Setters
{{- end}}