{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-with-autoupdate-and-ingress.serviceAccountName" . }}
  labels:
    {{- include "app-with-autoupdate-and-ingress.labels" . | nindent 4 }}
  # {{- with .Values.serviceAccount.annotations }}
  # annotations:
  #   {{- toYaml . | nindent 4 }}
  # {{- end }}
{{- end }}
