---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helmtest
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./examples/app-with-autoupdate-and-traefik-ingress/flux
  wait: true
  prune: true
  timeout: 10m