apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmtest
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: helmtest
  chart:
    spec:
      chart: app-with-autoupdate-and-traefik-ingress
      version: "0.1.5"
      sourceRef:
        kind: HelmRepository
        name: odit
        namespace: flux-system
      interval: 1m
  values:
    fullnameOverride: helmtest
    replicaCount: 1

    image:
      repository: nginx
      tag: "1.28.0" # {"$imagepolicy": "helmtest:helmtest:tag"}
      pullPolicy: IfNotPresent
      pullSecret: "" # Optional image pull secret will be used for deployment and image updater

    imageUpdater:
      enabled: true
      source:
        name: flux-system
        namespace: flux-system
        branch: main
        path: ./applications/niggl/helmtest
      filterTags: {}
      policy:
        semver:
          range: ">=1.28.0 <2.0.0"

    ingress:
      enabled: true
      dnsNames:
        - example.com
        - www.example.com
      tls:
        enabled: true
        clusterIssuerName: letsencrypt-prod

    service:
      type: ClusterIP
      port: 80

    serviceAccount:
      create: true

    resources: {}
    podSecurityContext: {}
    securityContext: {}